DATABASE_USER = '<DATABASE_USER>'
DATABASE_PASSWORD = '<DATABASE_PASSWORD>'
DATABASE_HOST = '<DATABASE_HOST>'
DATABASE_PORT = '<DATABASE_PORT>'
DATABASE_NAME = '<DATABASE_NAME>'
SECRET_KEY = '<SECRET_KEY>'
GCM_API_KEY = '<GCM_API_KEY>'
PROJECT_NAME = '<PROJECT_NAME>'

